### ISSUE TITLE
Token loosing "Cache" when updating the token properties like size

### ISSUE THREAD

**Issue by Malekal4699** [ggagnon76/token-independence#3]
PROBLEM STATEMENT
When opening the token's sheet by double left-clicking after the actor has been deleted, pressing the token button in the title, to the top right of the sheet, you change a parameter and then update. You can't open the sheet anymore.

ENVIRONMENT
Chrome
FVTT 0.8 (likely happens in 0.7 too)
windows 10

STEP TO REPRODUCE
1. Dupplicate Actor
2. Drag actor to canvas
3. Delete actor
4. Edit token properties and update.
5. Try to open sheet from token again.

POSSIBLE AVENUE
Could be linked to the Represented actor Field?

SCREENSHOTS
![image](https://user-images.githubusercontent.com/78604153/110126814-d0fef880-7d92-11eb-8867-30b0b60585e1.png)
![image](https://user-images.githubusercontent.com/78604153/110126826-d52b1600-7d92-11eb-8b81-093b8e32eb1a.png)
![image](https://user-images.githubusercontent.com/78604153/110126752-bf1d5580-7d92-11eb-96f4-b4d8286fb9f8.png)

**Comment by ggagnon76** [comment]
I always envisioned this module to be used while doing prep, not during actual gameplay.  When an actor is deleted, the token still has the actor ID in memory, and it is not until the canvas is updated (maybe the client?) that the token has the ID removed.  Until the canvas or client is updated, the token can open a character sheet because the synthetic actor still exists in memory. 

That being said, I don't know if editing the token properties, as demonstrated above, would cause the error regardless.  I need to test the following:
1) Does this happen in 0.7.9, since Malekal tested with 0.8.0?
2) Is this just an issue of the synthetic actor still pointing to the deleted actor ID?  
3) Does refreshing the page solve this issue?  (If so, a simple canvas.draw() in a actorDelete hook will resolve this)

**Comment by ggagnon76** [comment]
In 0.7.9, the token properties menu does not work at all once the token is fully in control of Token Independence.
The error message must be a 0.8.0 specific issue.
I will look into what I have to do to enable to token menu.

**Comment by Malekal4699** [comment]
Ok! my dev is on 0.8, but I guess I could've tried on 0.7 by making a new world...

**Comment by ggagnon76** [comment]
Error in console when trying to open the Token HUD on an independent token:

TypeError: An error occurred while rendering TokenConfig 40: Cannot read property 'randomImg' of undefined
