### ISSUE TITLE
Request to re-implement attach actor to token

### ISSUE THREAD

**Issue by dineshm72** [ggagnon76/token-independence#32]
Hi, I noticed that you removed the attach actor to broken token functionality in an earlier commit: https://github.com/ggagnon76/token-independence/commit/e2217c5ad2aad6200dc55225fc892b9732ead54f 

Presumably you had a reason for doing so.  But I just wanted to chime in that this functionality was one of the use cases I had been using the mod for, and I am bummed that it was removed.  So just wanted to make a request to re-enable it, if possible.

Thanks for considering!

**Comment by ggagnon76** [comment]
Hello,

I removed it because that functionality is now part of Core.  

I'm not currently able to open foundry, but here's the workflow as I remember it:
1) Right click on token and click on the gear in the Token Hud.
2) One of the selection boxes will be "actor" and should be empty if the token is 'broken'.
3) Simply click on the selection box and pick the actor from the list.  Core will re-attach the token to the actor.

**Comment by dineshm72** [comment]
Awesome, thanks for the pointer, I totally missed this.  It's slightly more cumbersome since you have to do each token individually as far as I can tell, but at least it's now possible.  Thanks!
